#! /usr/bin/env python
import argparse
from oneliner.runner import Runner


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('code', metavar='code', type=str, nargs='*',
                        help='code to run')
    parser.add_argument('-f', '--file', type=str)
    parser.add_argument('-d', '--debug', action='store_true')

    args = parser.parse_args()

    # AWK風に -f があればそれをスクリプトとして、
    # なければコマンドラインの一つ目をスクリプトとして解釈する。

    runner = Runner(args)
    if args.file:
        runner.run_file(args.file, args.code)
    elif len(args.code) == 0:
        runner.run_prompt()
    else:
        runner.run(args.code[0], args.code[1:])


if __name__ == "__main__":
    main()
